export default {
	show_id: 180,
	trending: [],
	action: [],
	adventure: [],
	comedy: [],
	drama: [],
	kids: [],
	romance: [],
	tapes: [
		{title: `Trending Now`},
		{title: `Because You Watched Peppa Pig`},
		{title: `Popular on Netflix`},
		{title: `Comedy`},
		{title: `Thriller`},
		{title: `Action`},
		{title: `Drama`},
		{title: `Adventure`},
		{title: `Romance`},
		{title: `Kids`},
	],
}
